DROP TABLE vidtc CASCADE;
DROP TABLE tiptr CASCADE;
DROP TABLE v_firm CASCADE;
DROP TABLE pts CASCADE;
DROP TABLE dmlavt CASCADE;
DROP TABLE dmapr CASCADE;


CREATE TABLE IF NOT EXISTS vidtc (
vidt INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
shname VARCHAR(10),
fullname VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS tiptr (
tid INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
tname VARCHAR(10),
vidt INTEGER REFERENCES vidtc(vidt),
prizngr VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS v_firm (
firmid INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
tlgr VARCHAR(10),
disloc VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS pts (
uin INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
unts VARCHAR(10),
tid INTEGER REFERENCES tiptr(tid),
firmid INTEGER REFERENCES v_firm(firmid),
grp NUMERIC,
normt NUMERIC,
datasp DATE
);

CREATE TABLE IF NOT EXISTS dmlavt (
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
uin INTEGER REFERENCES pts(uin),
serpl VARCHAR(20),
data DATE,
dataret DATE,
timebeg TIME,
timeend TIME,
worktime NUMERIC,
prostoy NUMERIC,
prostoytpr NUMERIC,
prostoygr NUMERIC,
speedb NUMERIC,
speede NUMERIC,
topid VARCHAR(10),
tostv NUMERIC,
tv NUMERIC,
ts NUMERIC,
tovz NUMERIC,
pergr NUMERIC,
pergrtkm NUMERIC
);

CREATE TABLE IF NOT EXISTS dmapr (
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
uin_pts INTEGER REFERENCES pts(uin),
pergr NUMERIC,
dml_id INTEGER REFERENCES dmlavt(id)
);
